/*
 * File: app/store/category.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.category', {
    extend: 'Ext.data.Store',

    config: {
        storeId: 'category',
        proxy: {
            type: 'jsonp',
            extraParams: {
                id: 'store_kukatpalli'
            },
            url: 'http://ec2-54-201-188-61.us-west-2.compute.amazonaws.com/mobileapp/category.php',
            reader: {
                type: 'json',
                rootProperty: 'result'
            }
        },
        fields: [
            {
                name: 'name'
            },
            {
                name: 'text'
            },
            {
                name: 'value'
            }
        ]
    }
});