/*
 * File: app/store/orders.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.orders', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.orders'
    ],

    config: {
        model: 'MyApp.model.orders',
        storeId: 'orders',
        proxy: {
            type: 'jsonp',
            url: 'http://ec2-54-201-188-61.us-west-2.compute.amazonaws.com/mobileapp/orders.php',
            reader: {
                type: 'json',
                rootProperty: 'result'
            }
        }
    }
});