/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        items: [
            {
                xtype: 'tabpanel',
                height: '100%',
                hidden: true,
                id: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'orders',
                        iconCls: 'more',
                        height: '100%',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'refresh',
                                ui: 'confirm',
                                text: 'refresh'
                            },
                            {
                                xtype: 'list',
                                height: '100%',
                                itemId: 'mylist',
                                width: '100%',
                                itemTpl: [
                                    '<tpl if="boolean == \'true\'">',
                                    '    ',
                                    '<table border="3" bordercolor="blue"  align="center">',
                                    '<tr>',
                                    '  <td><ul><li>Name:{customername}</li>',
                                    '      <li>Email:{email}</li>',
                                    '      <li>Address: abc,123,abc,123,adfadsfasdfsadfas,fasdf,asdf,asd,fasdf</li>',
                                    '      </ul>',
                                    '      ',
                                    '    ',
                                    '    </td>',
                                    '    <td><font size="5" color="blue" >{totalprice} ({totalproducts})</font></td>',
                                    '    ',
                                    '    </tr>',
                                    '    ',
                                    '    </tpl>',
                                    '    ',
                                    '    <tpl if="p == \'true\'">',
                                    ' <table width="100%" align="center">',
                                    '<tr>',
                                    '  <td>{productname}</td>',
                                    '  <td><font size="5" color="blue" >{productprice} ({productquantity})</font></td>',
                                    '    </tr>',
                                    '        </table>',
                                    '    </tpl>',
                                    '    ',
                                    '    <tpl if="b == \'true\'">     ',
                                    '    {button}',
                                    '     </tpl>',
                                    ''
                                ],
                                store: 'orders'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'products',
                        iconCls: 'more',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                items: [
                                    {
                                        xtype: 'searchfield',
                                        docked: 'top',
                                        itemId: 'mysearchfield',
                                        maxWidth: '',
                                        width: '100%',
                                        label: 'search',
                                        labelWidth: '20%',
                                        autoComplete: true
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                height: '100%',
                                itemId: 'mylist1',
                                itemTpl: [
                                    '<tpl if="pb == \'true\'">',
                                    ' ',
                                    '    <table width="100%" align="center">',
                                    '<tr>',
                                    '    <td rowspan="2">{productname}</td>',
                                    '    <td> {productprice} ({productquantity}) </td>',
                                    '        </tr>',
                                    ' 	',
                                    '    </table>',
                                    '    ',
                                    '    ',
                                    '</tpl>',
                                    '<tpl if="boolean == \'true\'">',
                                    '    <p align="center"><font size="5" color="blue"> {category} ({total}) </font></p>',
                                    ' ',
                                    '</tpl>',
                                    '',
                                    '<tpl if="ps == \'true\'">',
                                    '    <table width="100%" align="center">',
                                    '<tr>',
                                    '    <td>{setprice}</td>',
                                    '    <td>{setquantity}</td>',
                                    '        </tr>',
                                    '',
                                    '    </table>',
                                    '    ',
                                    '   ',
                                    '</tpl>',
                                    '',
                                    '<tpl if="b == \'true\'">',
                                    '   {button}',
                                    '</tpl>',
                                    '         ',
                                    '    ',
                                    '         ',
                                    ''
                                ],
                                store: 'products'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'add product',
                        iconCls: 'more',
                        items: [
                            {
                                xtype: 'formpanel',
                                height: '100%',
                                enctype: 'multipart/form-data',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'productname',
                                        label: 'name',
                                        name: 'productname'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'productprice',
                                        label: 'price',
                                        name: 'productprice'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'productquantity',
                                        label: 'quantity',
                                        name: 'productquantity'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        id: 'category',
                                        itemId: 'myselectfield',
                                        label: 'category',
                                        hiddenName: 'pi',
                                        listeners: [
                                            {
                                                fn: function(element, eOpts) {
                                                    var u=Ext.getCmp('user').getValue();
                                                    console.log(u);
                                                    var stre=Ext.getStore('category');
                                                    //stre.getProxy().setExtraParams({id:u});
                                                    //Ext.getStore('MyJsonPStore1').getProxy().setExtraParams({id:u});
                                                    //Ext.getStore('MyJsonPStore1').load();
                                                    //Ext.getStore('MyJsonPStore1').sync();

                                                    stre.load();
                                                    stre.sync();
                                                    var jsondata=[];
                                                    var num=stre.data.items.length;
                                                    console.log(num);
                                                    for(var ic = 0;ic<num;ic++){
                                                        var text=stre.getAt(ic).get('text');
                                                        var value=stre.getAt(ic).get('value');
                                                        var data={};
                                                        data.text=text;
                                                        data.value=value;
                                                        jsondata.push(data);    
                                                    }

                                                    //var jsonarr=JSON.parse(JSON.stringify(jsondata));
                                                    //console.log(jsonarr);
                                                    var slct=Ext.getCmp('category');
                                                    slct.setOptions(jsondata);

                                                },
                                                event: 'painted'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'filefield',
                                        id: 'file',
                                        label: 'image',
                                        name: 'file'
                                    },
                                    {
                                        xtype: 'button',
                                        handler: function(button, event) {
                                            this.up().submit({
                                                url: 'http://ec2-54-201-188-61.us-west-2.compute.amazonaws.com/mobileapp/addproduct.php',
                                                method: 'POST',
                                                waitTitle: 'Connecting',
                                                waitMsg: 'Sending data...',

                                                success: function (form, result) {
                                                    //debugger; //This block of code is not executing even after JSON response
                                                    var jsonoutput = Ext.decode(result);  // json parsing
                                                    console.log(jsonoutput);   
                                                    Ext.Msg.alert("Success");

                                                },
                                                failure: function (form, result) {//This block of code is not executing even after JSON response
                                                    Ext.Msg.alert('failure');
                                                    console.log(result);
                                                }



                                            });

                                        },
                                        text: 'add product'
                                    }
                                ]
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'bottom'
                }
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                hidden: false,
                id: 'title',
                title: 'Manage Your Store'
            },
            {
                xtype: 'textfield',
                border: 10,
                docked: 'top',
                hidden: false,
                id: 'user',
                label: 'Store',
                name: 'user',
                placeHolder: ''
            },
            {
                xtype: 'passwordfield',
                border: 3,
                docked: 'top',
                hidden: false,
                id: 'password',
                label: 'Password',
                name: 'password',
                placeHolder: ''
            },
            {
                xtype: 'button',
                centered: true,
                height: 48,
                hidden: false,
                id: 'login',
                itemId: 'mybutton8',
                minWidth: '70%',
                text: 'login'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton9Tap',
                event: 'tap',
                delegate: '#refresh'
            },
            {
                fn: 'onMylistItemTap',
                event: 'itemtap',
                delegate: '#mylist'
            },
            {
                fn: 'onMysearchfieldAction',
                event: 'action',
                delegate: '#mysearchfield'
            },
            {
                fn: 'onMylist1ItemTap',
                event: 'itemtap',
                delegate: '#mylist1'
            },
            {
                fn: 'onMybutton8Tap',
                event: 'tap',
                delegate: '#login'
            }
        ]
    },

    onMybutton9Tap: function(button, e, eOpts) {

        var u=Ext.getCmp('user').getValue();

        Ext.Msg.alert("hi", u);

        //var store = Ext.getStore('MyJsonPStore');
        //store.load();
        //store.getProxy().clear();
        //store.data.clear();
        Ext.getStore('orders').data.clear();
        Ext.getStore('orders').getProxy().setExtraParams({id:u});
        Ext.getStore('orders').load();
        Ext.getStore('orders').sync();
    },

    onMylistItemTap: function(dataview, index, target, record, e, eOpts) {
        var val=record.get('button');

        if(val)
        {
            console.log('button taped');
            var strtind=val.indexOf("id")+4;
            var endind=strtind;
            while(val.charAt(endind)!='-')
            endind++;
            var data=val.substr(strtind,endind-strtind);
            var n=val.charAt(endind+1);
            var i=index+1,j=0;
            Ext.getCmp('ext-simplelistitem-'+i).hide();
            i--;
            for(;j<=n;j++,i--)
            {
                //var btn=Ext.getCmp('ext-simplelistitem-'+i);
                //console.log(btn);
                Ext.getCmp('ext-simplelistitem-'+i).hide();
            }


            MyApp.app.getController('MyController').getid(data);

            Ext.Msg.alert("Good Job, Order ID is", data);

        }
    },

    onMysearchfieldAction: function(textfield, e, eOpts) {
        var value = textfield.getValue(),  
store = Ext.getStore('products');    //  getting the store that drives the contact list  

//first clear any current filters on thes tore  
store.clearFilter();  
var count=0;
//check if a value is set first, as if it isnt we dont have to do anything  
if (value) {  
    //the user could have entered spaces, so we must split them so we can loop through them all  
    var searches = value.split(' ');
    var regexps = [];  
    //loop them all  
    for (i = 0; i < searches.length; i++) {  
        //if it is nothing, continue  
        if (!searches[i]) continue;

        //if found, create a new regular expression which is case insenstive  
        regexps.push(new RegExp(searches[i], 'i'));  
    }
    var matched = []; 
    //now filter the store by passing a method  
    //the passed method will be called for each record in the store  
    Ext.getStore('products').filter(function(record) {  

        if(record.get('productname')){  

                var search = regexps[0],  
                didMatch = record.get('productname').match(search);

                //if it matched the first or last name, push it into the matches array  
                matched[1]=didMatch;
            if(didMatch)
            {
                count++;
                    console.log("p_name count:"+count+","+didMatch);
                    return matched[1];  
            }
            }
        if(record.get('setprice')&& count==1){  
            didMatch2 = record.get('setprice');
            //if it matched the first or last name, push it into the matches array  
            matched[1]=didMatch2;
            //else true true (show in the store) 
            count++;
            return matched[1];  

        }
        if(record.get('button')&& count==2){  
            didMatch3 = record.get('button');
            //if it matched the first or last name, push it into the matches array  
            matched[1]=didMatch3;
            //else true true (show in the store) 
            count=0;
            return matched[1];  

        }
    });
}  

    },

    onMylist1ItemTap: function(dataview, index, target, record, e, eOpts) {
        var val=record.get('button');


        if(val)
        {

            var strtind=val.indexOf("id")+4;
            var endind=strtind;
            while(val.charAt(endind)!='-')
            endind++;

            var data=val.substr(strtind,endind-strtind);

            var strtind2=val.indexOf("name")+6;
            var endind2=strtind2;
            while(val.charAt(endind2)!='-')
            endind2++;

            var data2=val.substr(strtind2,endind2-strtind2);

            if(typeof MyApp.app.textdata[data2] == 'undefined' || typeof MyApp.app.textdata[data2-1] == 'undefined')
            Ext.Msg.alert("Please enter some value for this product");


            console.log("product id:"+data+"array ind"+data2);
            MyApp.app.getController('MyController').updateproduct(data, data2);




        }
    },

    onMybutton8Tap: function(button, e, eOpts) {
        var u=Ext.getCmp('user').getValue();
        var p=Ext.getCmp('password').getValue();
        if( u && p){
            var jsondata={};
            jsondata.un=u;
            jsondata.pd=p;
            Ext.Ajax.request({
                url:'http://ec2-54-201-188-61.us-west-2.compute.amazonaws.com/mobileapp/login.php',
                method:'POST',
                params:jsondata,
                success: function(response){
                    var t=(response.responseText).valueOf();

                    if(t.match("fail")) Ext.Msg.alert("Please enter correct user and Password");

                    else {        
                        console.log('success'); 

                        Ext.getCmp('login').hide();
                        Ext.getCmp('user').hide();
                        Ext.getCmp('password').hide();
                        Ext.getCmp('title').hide();


                        // load orders to the jsonP store
                        Ext.getStore('orders').getProxy().setExtraParams({id:u});
                        Ext.getStore('products').getProxy().setExtraParams({id:u});
                        Ext.getStore('category').getProxy().setExtraParams({id:u});
                        Ext.getStore('orders').load();
                        Ext.getStore('products').load();
                        Ext.getStore('category').load();

                        Ext.getCmp('tabpanel').show();



                        console.log("store is loaded");


                    }

                },
                failure: function(response){
                    console.log('failure');
                    Ext.Msg.alert("check the connection");
                }



            });

        }

        else { Ext.Msg.alert("dude, what are you doing?");}

    }

});