/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
    },

    func1: function(val, id) {
        console.log("val :"+val+"id :"+id);

        MyApp.app.textdata[id]=val;

        console.log("array defined"+MyApp.app.textdata);
        //if(name=="price"){ gprice=val;}
        //if(name=="qty"){gqty=val;}
    },

    updateproduct: function(id, ar) {

        console.log("id is: "+id+"  arraya: "+ar);
        console.log(MyApp.app.textdata);
        var jsondata={};
        jsondata.price= MyApp.app.textdata[ar-1];
        jsondata.qty= MyApp.app.textdata[ar];
        jsondata.id=id;

        console.log("price: "+jsondata.price+"  qty: "+jsondata.qty+"  id:"+jsondata.id);

        Ext.Ajax.request({
            method: 'POST',
            params:jsondata,
            url:'http://ec2-54-201-188-61.us-west-2.compute.amazonaws.com/mobileapp/updateproduct.php',

            success : function(response){
                console.log("data is sent to file");
                console.log(response.responseText);
                Ext.Msg.alert("Product updated");
            },
            failure: function(response){
                Ext.Msg.alert("Oops, product not updated: Enter again");
            }
        });


    },

    getid: function(data) {
        Ext.Ajax.request({
            url: 'http://ec2-54-201-188-61.us-west-2.compute.amazonaws.com/mobileapp/updateorder.php',
            method: 'POST',
            params: {
                id: data
            },

            success: function(response) {
                // Ext.Msg.alert("Confirmation is sent to shopper, order ID ", response.responseText);
                console.log("sucess");
                //Ext.Msg.alert('Link Shortened', Ext.JSON.decode(response).toString(), function() {
                //form.reset();
                console.log("reset");

            },
            failure: function(response) {
                Ext.Msg.alert('Error', Ext.JSON.decode(response).toString(), function() {
                    //form.reset();
                    console.log("error");
                });
            }
        });
    }

});